# Generated by Django 2.2.7 on 2019-11-09 13:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191109_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+919999999999', max_length=128, null=True, region=None),
        ),
    ]
