# Generated by Django 2.2.7 on 2019-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191109_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='+919999999999', max_length=14, null=True),
        ),
    ]
