# Generated by Django 2.2.7 on 2019-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191110_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('TECHNICAL', 'TECHNICAL'), ('NON-TECHNICAL', 'NON-TECHNICAL')], default='', help_text='Enter Event Type (e.g. TECHNICAL)', max_length=20),
        ),
        migrations.DeleteModel(
            name='Event_Type',
        ),
    ]
