# Generated by Django 2.2.7 on 2019-11-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191110_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(default=' ', help_text='Enter a brief description of the event', max_length=1000),
        ),
    ]
