# Generated by Django 2.2.7 on 2019-11-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191110_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Non_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name_non_tech', models.CharField(choices=[('KAVYANIKAL', 'KAVYANIKAL'), ('SOLICIT', 'SOLICIT'), ('HINDI DEBATE', 'HINDI DEBATE'), ('ENGLISH DEBATE', 'ENGLISH DEBATE'), ('PPT', 'PPT'), ('SELFIVATION', 'SELFIVATION'), ('CAPTURE THE MOMENT', 'CAPTURE THE MOMENT'), ('DANGORIUS', 'DANGORIUS'), ('MIX CRICKET', 'MIX CRICKET'), ('FUTSAL', 'FUTSAL'), ('ARM WRESTLING', 'ARM WRESTLING'), ('BLIND HURDLE', 'BLIND HURDLE'), ('TUG OF WAR', 'TUG OF WAR'), ('MUSICAL CHAIR', 'MUSICAL CHAIR'), ('SKETHCHING', 'SKETHCHING'), ('WALL PAINTING', 'WALL PAINTING'), ('STREET PAINTING', 'STREET PAINTING'), ('RANGOLI', 'RANGOLI'), ('TREASURE HUNT', 'TREASURE HUNT'), ('AD-MAD', 'AD-MAD'), ('SNAKE & LADDER', 'SNAKE & LADDER'), ('PUBG', 'PUBG'), ('NEED FOR SPEED', 'NEED FOR SPEED'), ('TEKKEN', 'TEKKEN'), ('DRAG RACE', 'DRAG RACE'), ('DART', 'DART'), ('KNOW YOUR PARTNER', 'KNOW YOUR PARTNER'), ('THE RUBIKS CUBE', 'THE RUBIKS CUBE')], help_text='Enter Event Name (e.g. CodeGolf)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name_tech', models.CharField(choices=[('AUTO QUIZ', 'AUTO QUIZ'), ('BRIDGE IT', 'BRIDGE IT'), ('BUG-D-CODE', 'BUG-D-CODE'), ('C-LEGACY', 'C-LEGACY'), ('CANVAS', 'CANVAS'), ('CIRCUITEX', 'CIRCUITEX'), ('CODE GOLF', 'CODE GOLF'), ('CODERVATION', 'CODERVATION'), ('DAVIT', 'DAVIT'), ('E-QUIZ', 'E-QUIZ'), ('FAST BOOT', 'FAST BOOT'), ('HURDLE MANIA', 'HURDLE MANIA'), ('IDENTOKIT', 'IDENTOKIT'), ('MODULA', 'MODULA'), ('PATHIK', 'PATHIK'), ('ROBO SOCCER', 'ROBO SOCCER'), ('ROBO WAR', 'ROBO WAR'), ('ROCKET PROPULSION', 'ROCKET PROPULSION'), ('SMART IDEA', 'SMART IDEA'), ('TECH QUIZ', 'TECH QUIZ'), ('TYPE RACER', 'TYPE RACER'), ('UNCHAINED REACTION', 'UNCHAINED REACTION'), ('WEB DEXTRO', 'WEB-DEXTRO')], help_text='Enter Event Name (e.g. CodeGolf)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participation_NonTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Event_Non_Technical')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Participation_Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Event_Technical')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Event_Choices',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
