# Generated by Django 2.2.7 on 2019-11-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191111_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
